CXX = g++

CXXFLAGS = -g - Wall - std = c++11

TARGET = bst_test

SRC = main.cpp

DEPS = BST.h

all : $(TARGET)

$(TARGET) : $(SRC) $(DEPS)
$(CXX) $(CXXFLAGS) - o $(TARGET) $(SRC)

clean :
rm - f $(TARGET)
